CREATE DATABASE IF NOT EXISTS `hbndb`;
USE `hbndb`;

DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(20) DEFAULT NULL,
   `salary` DOUBLE NOT NULL,
   PRIMARY KEY (`id`)
);
